```{r load libs}
library(GENESPACE)
library(data.table)
```
```{r load gpar}
gpar <- readRDS("/bigdata/armstronglab/respl001/side_quests/snow_leopard/SnowLeopardSynteny/results/cats/rds/gpar.rds")
gparam <- readRDS("/bigdata/armstronglab/respl001/side_quests/snow_leopard/SnowLeopardSynteny/results/cats/rds/genespace_out.rds")
```
```{r invert}
invars <- list(
  leopard = c("79", "190", "24", "124", "13", "2", "338", "1", "112", "223", "316", "327"),
  clouded_leopard = c("11", "4", "5", "2", "8", "12", "16", "1", "9"),
  jaguar = c("6", "10", "5", "12", "14", "8", "9", "4", "2")
)
invchr <- data.table(
  genome = rep(names(invars), lengths(invars)),
  chr = unlist(invars)
)
```
```{r set ref}
# plot base pair rip
rip <- plot_riparian(
  gsParam = gparam,
  useOrder = FALSE,
  refGenome = "domestic_cat",
  # inversionColor = "red",
  genomeIDs = c(
    "snow_leopard",
    "tiger",
    "leopard",
    "lion",
    "jaguar",
    "clouded_leopard",
    "domestic_cat"
  ),
  customRefChrOrder = c(
    "A1","A2","A3",
    "B1","B2","B3","B4",
    "C1","C2",
    "D1","D2","D3","D4",
    "E1","E2","E3",
    "F1","F2",
    "X"
  ),
  minChrLen2plot = 1e7,
  # syntenyWeight = 0,
  invertTheseChrs = invchr,
  pdfFile = "/bigdata/armstronglab/respl001/side_quests/snow_leopard/SnowLeopardSynteny/domestic_cat_custom.rip.bp.pdf",
  forceRecalcBlocks = FALSE
)
```
